export const ahadith = [
  "“It will be said to the companion of the Qur’aan: Recite and rise in status, recite as you used to recite in the world, for your status will be at the last verse that you recite.”",
  "“The likeness of the one who reads Qur’aan and memorizes it is that he is with the righteous honourable scribes. The likeness of the one who reads it and tries hard to memorize it even though it is difficult for him, he will have two rewards.”",
  "“Fasting and the Qur’aan will intercede for a person on the Day of Resurrection. Fasting will say, ‘O Lord, I deprived him of food and desires during the day, so let me intercede for him.’ The Qur’aan will say, ‘O Lord I deprived him of his sleep at night, so let me intercede for him.’ Then they will both intercede for him.”",
  "“The bearer of the Qur’aan, if he regards what it permits as halaal and what it forbids as haraam, he will intercede for ten of his family members on the Day of Resurrection, all of whom deserved to enter Hell(Hadith Da'eef).”",
  "“When the first Muhaajirun (emigrants) came to Quba, before the Messenger of Allah (peace and blessings of Allah be upon him) came (to Madinah), Salim the freed slave of Abu Hudhayfah used to lead them in prayer, and he was the one who knew the most Quran.” ",
  "“The Prophet would wrap two of the men slain at Uhud in a single cloth, then he would ask, ‘Which of them knew more Quran?’ If one of them was pointed out to him, he would put that one in the lahd (niche in the side of the grave) first. And he said, ‘I will be a witness over these people on the Day of Resurrection.’ He commanded that they should be buried with their blood, without being washed, and that no funeral prayer should be offered for them.” ",
  "‘Amir ibn Wathilah narrated that Nafi’ ibn ‘Abd al-Harith met ‘Umar in ‘Usfan, and ‘Umar had appointed him as governor of Makkah. ‘Umar said, “Who have you appointed in charge of the people of the valley?” He said, “Ibn Abza.” ‘Umar asked, “Who is Ibn Abza?” He said, “One of our freed slaves.” Umar said, “Have you appointed over them a freed slave?!” He said, “He is well-versed in the Book of Allah and he has knowledge of the laws of inheritance.” ‘Umar said: “Your Prophet (peace and blessings of Allah be upon him) said: ‘Indeed, by this Book, Allah would exalt some people and degrade others.’”",
  "“The Quran will come on the Day of Resurrection and will say, ‘O Lord, adorn him.’ So he will be given a crown of honour to wear. Then it will say, ‘O Lord, give him more.’ So he will be given a garment of honour.’ Then it will say, ‘O Lord, be pleased with him.’ So Allah will be pleased with him. Then it will be said to him, ‘Recite and advance in status, and for each verse you will gain one more hasanah (reward for good deed).”",
  "Abu Umamah al-Bahili said: “I heard the Messenger of Allah (peace and blessings of Allah be upon him) say, ‘Recite the Quran, for it will come on the Day of Resurrection to intercede for its companions . Recite the two bright ones, al-Baqarah and Surah Al ‘Imran, for they will come on the Day of Resurrection like two clouds or two shades or two flocks of birds in ranks, pleading for those who recite them. Recite Surah al-Baqarah for to take recourse to it is a blessing and to give it up is a cause of grief, and the magicians cannot confront it.” ",
  "Abu Hurayrah said: “The Messenger of Allah (peace and blessings of Allah be upon him) said: ‘The Quran will come on the Day of Resurrection like a pale man saying to its companion, “Do you recognize me? I am the one who made you stay up at night and made you thirsty during the day…” Then he will be given dominion in his right hand and eternity in his left, and a crown of dignity will be placed upon his head, and his parents will be clothed with garments which far surpass everything to be found in this world. They will say, “O Lord, how did we earn this.” It will be said to them, “Because you taught your child the Quran.”",
  "Buraydah said: “The Messenger of Allah (peace and blessings of Allah be upon him) said: ‘Whoever reads the Quran, learns it and acts in accordance with it, on the Day of Resurrection his parents will be given a crown to wear whose light will be like the light of the sun, and his parents will be given garments which far surpass everything to be found in this world. They will say, “Why have we been given this to wear?” It will be said, “Because your child learned the Quran.”",
];
