type ISurahData = [
  suraNumber: number,
  transliteration: string,
  englishName: string,
  revelation: string,
];

export const SURAH_DATA: ISurahData[] = [
  [1, "Al-Faatiha", "The Opening", "Meccan"],
  [2, "Al-Baqara", "The Cow", "Medinan"],
  [3, "Aal-i-Imraan", "The Family of Imraan", "Medinan"],
  [4, "An-Nisaa", "The Women", "Medinan"],
  [5, "Al-Maaida", "The Table", "Medinan"],
  [6, "Al-An'aam", "The Cattle", "Meccan"],
  [7, "Al-A'raaf", "The Heights", "Meccan"],
  [8, "Al-Anfaal", "The Spoils of War", "Medinan"],
  [9, "At-Tawba", "The Repentance", "Medinan"],
  [10, "Yunus", "Jonas", "Meccan"],
  [11, "Hud", "Hud", "Meccan"],
  [12, "Yusuf", "Joseph", "Meccan"],
  [13, "Ar-Ra'd", "The Thunder", "Medinan"],
  [14, "Ibrahim", "Abraham", "Meccan"],
  [15, "Al-Hijr", "The Rock", "Meccan"],
  [16, "An-Nahl", "The Bee", "Meccan"],
  [17, "Al-Israa", "The Night Journey", "Meccan"],
  [18, "Al-Kahf", "The Cave", "Meccan"],
  [19, "Maryam", "Mary", "Meccan"],
  [20, "Taa-Haa", "Taa-Haa", "Meccan"],
  [21, "Al-Anbiyaa", "The Prophets", "Meccan"],
  [22, "Al-Hajj", "The Pilgrimage", "Medinan"],
  [23, "Al-Muminoon", "The Believers", "Meccan"],
  [24, "An-Noor", "The Light", "Medinan"],
  [25, "Al-Furqaan", "The Criterion", "Meccan"],
  [26, "Ash-Shu'araa", "The Poets", "Meccan"],
  [27, "An-Naml", "The Ant", "Meccan"],
  [28, "Al-Qasas", "The Stories", "Meccan"],
  [29, "Al-Ankaboot", "The Spider", "Meccan"],
  [30, "Ar-Room", "The Romans", "Meccan"],
  [31, "Luqman", "Luqman", "Meccan"],
  [32, "As-Sajda", "The Prostration", "Meccan"],
  [33, "Al-Ahzaab", "The Clans", "Medinan"],
  [34, "Saba", "Sheba", "Meccan"],
  [35, "Faatir", "The Originator", "Meccan"],
  [36, "Yaseen", "Yaseen", "Meccan"],
  [37, "As-Saaffaat", "Those drawn up in Ranks", "Meccan"],
  [38, "Saad", "The letter Saad", "Meccan"],
  [39, "Az-Zumar", "The Groups", "Meccan"],
  [40, "Al-Ghaafir", "The Forgiver", "Meccan"],
  [41, "Fussilat", "Explained in detail", "Meccan"],
  [42, "Ash-Shura", "Consultation", "Meccan"],
  [43, "Az-Zukhruf", "Ornaments of gold", "Meccan"],
  [44, "Ad-Dukhaan", "The Smoke", "Meccan"],
  [45, "Al-Jaathiya", "Crouching", "Meccan"],
  [46, "Al-Ahqaf", "The Dunes", "Meccan"],
  [47, "Muhammad", "Muhammad", "Medinan"],
  [48, "Al-Fath", "The Victory", "Medinan"],
  [49, "Al-Hujuraat", "The Inner Apartments", "Medinan"],
  [50, "Qaaf", "The letter Qaaf", "Meccan"],
  [51, "Adh-Dhaariyat", "The Winnowing Winds", "Meccan"],
  [52, "At-Tur", "The Mount", "Meccan"],
  [53, "An-Najm", "The Star", "Meccan"],
  [54, "Al-Qamar", "The Moon", "Meccan"],
  [55, "Ar-Rahmaan", "The Beneficent", "Medinan"],
  [56, "Al-Waaqia", "The Inevitable", "Meccan"],
  [57, "Al-Hadid", "The Iron", "Medinan"],
  [58, "Al-Mujaadila", "The Pleading Woman", "Medinan"],
  [59, "Al-Hashr", "The Exile", "Medinan"],
  [60, "Al-Mumtahana", "She that is to be examined", "Medinan"],
  [61, "As-Saff", "The Ranks", "Medinan"],
  [62, "Al-Jumu'a", "Friday", "Medinan"],
  [63, "Al-Munaafiqoon", "The Hypocrites", "Medinan"],
  [64, "At-Taghaabun", "Mutual Disillusion", "Medinan"],
  [65, "At-Talaaq", "Divorce", "Medinan"],
  [66, "At-Tahrim", "The Prohibition", "Medinan"],
  [67, "Al-Mulk", "The Sovereignty", "Meccan"],
  [68, "Al-Qalam", "The Pen", "Meccan"],
  [69, "Al-Haaqqa", "The Reality", "Meccan"],
  [70, "Al-Ma'aarij", "The Ascending Stairways", "Meccan"],
  [71, "Nooh", "Noah", "Meccan"],
  [72, "Al-Jinn", "The Jinn", "Meccan"],
  [73, "Al-Muzzammil", "The Enshrouded One", "Meccan"],
  [74, "Al-Muddaththir", "The Cloaked One", "Meccan"],
  [75, "Al-Qiyaama", "The Resurrection", "Meccan"],
  [76, "Al-Insaan", "Man", "Medinan"],
  [77, "Al-Mursalaat", "The Emissaries", "Meccan"],
  [78, "An-Naba", "The Announcement", "Meccan"],
  [79, "An-Naazi'aat", "Those who drag forth", "Meccan"],
  [80, "Abasa", "He frowned", "Meccan"],
  [81, "At-Takwir", "The Overthrowing", "Meccan"],
  [82, "Al-Infitaar", "The Cleaving", "Meccan"],
  [83, "Al-Mutaffifin", "Defrauding", "Meccan"],
  [84, "Al-Inshiqaaq", "The Splitting Open", "Meccan"],
  [85, "Al-Burooj", "The Constellations", "Meccan"],
  [86, "At-Taariq", "The Morning Star", "Meccan"],
  [87, "Al-A'laa", "The Most High", "Meccan"],
  [88, "Al-Ghaashiya", "The Overwhelming", "Meccan"],
  [89, "Al-Fajr", "The Dawn", "Meccan"],
  [90, "Al-Balad", "The City", "Meccan"],
  [91, "Ash-Shams", "The Sun", "Meccan"],
  [92, "Al-Lail", "The Night", "Meccan"],
  [93, "Ad-Dhuhaa", "The Morning Hours", "Meccan"],
  [94, "Ash-Sharh", "The Consolation", "Meccan"],
  [95, "At-Tin", "The Fig", "Meccan"],
  [96, "Al-Alaq", "The Clot", "Meccan"],
  [97, "Al-Qadr", "The Power, Fate", "Meccan"],
  [98, "Al-Bayyina", "The Evidence", "Medinan"],
  [99, "Az-Zalzala", "The Earthquake", "Medinan"],
  [100, "Al-Aadiyaat", "The Chargers", "Meccan"],
  [101, "Al-Qaari'a", "The Calamity", "Meccan"],
  [102, "At-Takaathur", "Competition", "Meccan"],
  [103, "Al-Asr", "The Declining Day, Epoch", "Meccan"],
  [104, "Al-Humaza", "The Traducer", "Meccan"],
  [105, "Al-Fil", "The Elephant", "Meccan"],
  [106, "Quraish", "Quraysh", "Meccan"],
  [107, "Al-Maa'un", "Almsgiving", "Meccan"],
  [108, "Al-Kawthar", "Abundance", "Meccan"],
  [109, "Al-Kaafiroon", "The Disbelievers", "Meccan"],
  [110, "An-Nasr", "Divine Support", "Medinan"],
  [111, "Al-Masad", "The Palm Fibre", "Meccan"],
  [112, "Al-Ikhlaas", "Sincerity", "Meccan"],
  [113, "Al-Falaq", "The Dawn", "Meccan"],
  [114, "An-Naas", "Mankind", "Meccan"],
];
